feat: build with deno; improve theme coverage
catppuccin/thunderbird pull request #8
Opened 2024-02-24 01:29 UTC by nullishamy

This brings the build system up to date with current Catppuccin tech, improves the coverage of the theme, and overall improves the quality of things.

2024-02-24 01:44 UTC, uncenter commented on build.ts
> +            id: `theme@catppuccinorg.com`,
```suggestion
            id: `thunderbird@catppuccin.com`,
```

2024-02-24 01:44 UTC, uncenter commented on build.ts
> +        description: `Catppuccin theme for Thunderbird - ${titleCase(
```suggestion
        description: `Soothing pastel theme for Thunderbird - ${titleCase(
```
Not sure if that sort of description format would work here? :p

2024-02-24 02:13 UTC, sgoudham commented on build.ts
> +            id: `theme@catppuccinorg.com`,
Would this not be an actual email address that we have? E.g.  `releases@catppuccin.com`

2024-02-24 02:55 UTC, uncenter commented on build.ts
> +            id: `theme@catppuccinorg.com`,
I think it doesn't have to be an actual email lol.

2024-02-24 14:48 UTC, nullishamy commented on build.ts
> +            id: `theme@catppuccinorg.com`,
Thunderbird enforces some scheme similar to email through a regex. Haven't quite thought about what this should actually be yet. Worth noting that #5 should be solved here.

2024-02-24 18:49 UTC, sgoudham commented on build.ts
> +            id: `theme@catppuccinorg.com`,
From Thunderbird's [A Guide To Theming](https://developer.thunderbird.net/add-ons/web-extension-themes):

<img width="776" alt="image" src="https://github.com/catppuccin/thunderbird/assets/58985301/bbdc885a-21d1-4ccb-80e9-c7fc333ef369">

2024-02-25 16:35 UTC, sgoudham requested changes

2024-02-25 16:35 UTC, sgoudham commented on flake.nix
> +}
Do we need `just` or `whiskers` here?

```suggestion
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-23.11";
    flake-utils.url = "github:numtide/flake-utils";
  };

  description = "Development shell flake";
  outputs = { self, nixpkgs, flake-utils }: flake-utils.lib.eachDefaultSystem (system: {
    devShell = let 
      pkgs = nixpkgs.legacyPackages.${system};
    in 
      pkgs.mkShell {
        packages = with pkgs; [
          deno
        ];
      };
  });
}
```

2024-02-25 16:35 UTC, sgoudham commented on build.ts
> +// DON'T CHANGE THIS :OMEGALUL:
Sorry, meant to change this comment before pushing yesterday.

```suggestion
// Allows for the UUIDs to be "seeded" and therefore reproducible
// DO NOT CHANGE
```

2024-02-25 16:35 UTC, sgoudham commented on build.ts
> +    await zip.writeZip(`./themes/${name}/${name}-${accent}.xpi`);
Are we sure that we want the directory structure to be like `mocha/mocha-blue`? I'm not entirely fussed but just looked odd at a glance.

2024-02-25 16:47 UTC, uncenter approved these changes

2024-02-25 16:47 UTC, uncenter commented on build.ts
> +    await zip.writeZip(`./themes/${name}/${name}-${accent}.xpi`);
Ooh right :eyes:

2024-02-25 16:49 UTC, nullishamy commented on build.ts
> +    await zip.writeZip(`./themes/${name}/${name}-${accent}.xpi`);
I prefer the names being more descriptive, and we will more than likely condense the entire port into 1 XPI in the future, as discussed on Discord. I think for the time being this is fine?

2024-02-25 16:55 UTC, sgoudham approved these changes

2024-02-25 16:56 UTC, merged